AUDIT_CONFIG = {
    "browser": {
        "headless": False,
        "browserType": "chromium",
        "channel": "chrome",
        "slowMoMs": 120,
        "ignoreHttpsErrors": True,
        "viewport": {
            "width": 1440,
            "height": 900,
        },
    },
    "navigation": {
        "timeoutMs": 15000,
        "waitUntil": "domcontentloaded",
        "postLoadDelayMs": 300,
    },
    "pageReadiness": {
        "networkIdleTimeoutMs": 4000,
        "assetTimeoutMs": 5000,
        "settleDelayMs": 350,
    },
    "paths": {
        "inputFile": "shared/generated/website_menu.json",
        "screenshotDir": "shared/output/screenshots",
        "resultsDir": "shared/output/results",
    },
    "outputCleanup": {
        "clearWebsiteScreenshotsBeforeRun": True,
        "keepDebugArtifacts": False,
    },
    "screenshot": {
        "fullPage": True,
        "type": "png",
    },
    "pageCapture": {
        "dismissCookieBanners": True,
        "captureScrollScreenshots": True,
        "scrollMaxRounds": 4,
        "saveDomSnapshot": True,
        "saveNetworkLog": True,
    },
    "presentationChecks": {
        "runtimeMotion": {
            "enabled": True,
            "sampleIntervalMs": 350,
            "sampleCount": 4,
            "motionThresholdPx": 6,
            "opacityThreshold": 0.2,
            "maxElements": 120,
        },
    },
    "urlNormalization": {
        "removeHash": True,
        "removeTrailingSlash": False,
        "removeCommonTrackingParams": True,
        "trackingParams": [
            "utm_source",
            "utm_medium",
            "utm_campaign",
            "utm_term",
            "utm_content",
            "gclid",
            "fbclid",
        ],
    },
    "inputParsing": {
        "includeHomepage": True,
        "includeAuthPages": False,
        "includeNavbarUrls": True,
        "includeSectionUrls": True,
    },
    "clickableDetection": {
        "selectors": [
            "a[href]",
            "button",
            '[role="button"]',
            'input[type="button"]',
            'input[type="submit"]',
        ],
        "maxElementsPerPage": 500,
    },
    "classification": {
        "forbiddenKeywords": [
            "logout",
            "log out",
            "sign out",
            "delete",
            "remove",
            "remove account",
            "deactivate",
            "unsubscribe",
            "pay",
            "buy",
            "purchase",
            "checkout",
            "place order",
            "confirm",
            "submit",
            "send",
            "save",
            "publish",
            "reset",
            "clear cart",
            "cancel subscription",
            "close account",
            "login",
            "log in",
            "connexion",
            "se connecter",
            "sign in",
            "register",
            "sign up",
        ],
        "safeKeywords": [
            "home",
            "about",
            "contact",
            "learn more",
            "read more",
            "details",
            "view details",
            "open",
            "menu",
            "next",
            "previous",
            "back",
            "search",
            "filter",
            "sort",
            "show more",
            "see more",
        ],
        "forbiddenHrefKeywords": [
            "logout",
            "signout",
            "delete",
            "remove",
            "checkout",
            "payment",
            "purchase",
            "unsubscribe",
            "deactivate",
            "login",
            "customer_authentication",
            "cart",
            "register",
            "signup",
            "signin",
        ],
    },
    "renderedUi": {
        "enabled": True,
        "selectors": [
            "html",
            "body",
            "header",
            "nav",
            "main",
            "footer",
            "section",
            "article",
            "aside",
            "form",
            "fieldset",
            "legend",
            "label",
            "input",
            "textarea",
            "select",
            "option",
            "button",
            '[role="button"]',
            "a",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "p",
            "ul",
            "ol",
            "li",
            "table",
            "thead",
            "tbody",
            "tr",
            "td",
            "th",
            "dialog",
            '[role="dialog"]',
            '[role="alert"]',
            '[role="tab"]',
            '[role="tabpanel"]',
            '[role="navigation"]',
            '[role="main"]',
            '[role="form"]',
            "[data-testid]",
            "[class*='card']",
            "[class*='modal']",
            "[class*='dialog']",
            "[class*='form']",
            "[class*='input']",
            "[class*='field']",
            "[class*='button']",
        ],
        "maxElementsPerPage": 300,
    },
    "interactionTesting": {
        "enabled": True,
        "onlyVisible": True,
        "maxSafeInteractionsPerPage": None,
        "actionTimeoutMs": 5000,
        "postClickDelayMs": 250,
        "testSamePageAnchors": False,
        "skipExternalOrigins": True,
        "captureAllInteractionScreenshots": True,
        "captureSuccessfulInteractionScreenshots": True,
    },
    "execution": {
        "pageConcurrency": 5,
    },
        "mobileAudit": {
        "appium": {
            "url": "http://127.0.0.1:4723",
            "platformName": "Android",
            "automationName": "UiAutomator2",
            "deviceName": "Android Emulator",
            "newCommandTimeoutSec": 120,
            "adbExecTimeoutMs": 120000,
            "uiautomator2ServerInstallTimeoutMs": 120000,
            "uiautomator2ServerLaunchTimeoutMs": 120000,
            "uiautomator2ServerReadTimeoutMs": 120000,
            "androidInstallTimeoutMs": 120000,
            "appWaitDurationMs": 120000,
            "skipDeviceInitialization": False,
            "disableWindowAnimation": True,
            "deviceReadyTimeoutMs": 180000,
            "deviceReadyPollMs": 2000,
            "autoGrantPermissions": True,
            "noReset": True,
        },
        "capture": {
            "launchTimeoutMs": 15000,
            "settleDelayMs": 1200,
            "stabilizationTimeoutMs": 10000,
            "stabilizationPollMs": 700,
        },
        "paths": {
            "outputRoot": "shared/generated/mobile-audits",
            "screenshotDirName": "screenshots",
            "hierarchyDirName": "hierarchies",
        },
    },
}
